"""add drawing option `reversal`

Revision ID: 9a8c61986896
Revises: b7b8577fe9d6
Create Date: 2022-01-19 18:27:00.534166

"""
import sqlalchemy as sa

from alembic import op

from bearzzzbot.drawings.models import Drawing

# revision identifiers, used by Alembic.
revision = "9a8c61986896"
down_revision = "b7b8577fe9d6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("drawings", sa.Column("reversal", sa.Boolean(), nullable=True))
    update_stmt = (
        sa.update(Drawing)
        .values(
            reversal=True,
        )
        .where(Drawing.reversal.is_(sa.null()))
    )
    conn = op.get_bind()
    conn.execute(update_stmt)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("drawings", "reversal")
    # ### end Alembic commands ###
