"""init

Revision ID: b7b8577fe9d6
Revises: 
Create Date: 2022-01-15 19:53:26.565926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7b8577fe9d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drawings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('wood', sa.Boolean(), nullable=True),
    sa.Column('fire', sa.Boolean(), nullable=True),
    sa.Column('one', sa.Boolean(), nullable=True),
    sa.Column('two', sa.Boolean(), nullable=True),
    sa.Column('three', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('drawings_pk'))
    )
    op.create_index(op.f('ix_drawings_owner'), 'drawings', ['owner'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drawings_owner'), table_name='drawings')
    op.drop_table('drawings')
    # ### end Alembic commands ###
